services:
  aiwolf-agent:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
    container_name: AIWOLF_AGENT
    volumes:
      - ./src/Agent:/Agent
    ports:
      - "50000-50004:50000-50004"
    tty: true
